# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Aji Kisworo Mukti
tagline:          'Blog'
description:      ''
url:              http://hyde.getpoole.com

author:
  name:           'Aji Kisworo Mukti'
  url:            https://twitter.com/Cengkarux

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/adzymaniac